import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";
import lightBulB from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import { useState } from "react";
import emailjs from "emailjs-com";

export default function Home() {
  const [isContactFormOpen, setIsContactFormOpen] = useState(false);

  // Function to handle opening the contact form
  const handleOpenContactForm = () => {
    setIsContactFormOpen(true);
  };

  function sendEmail(e) {
    e.preventDefault(); //This is important, i'm not sure why, but the email won't send without it

    emailjs
      .sendForm(
        "service_o4x1czt",
        "template_savk2cf",
        e.target,
        "gWpUX5aYXqjcZPRhA"
      )
      .then(
        (result) => {
          window.location.reload(); //This is if you still want the page to reload (since e.preventDefault() cancelled that behavior)
        },
        (error) => {
          console.log(error.text);
        }
      );
  }
  return (
    <>
      <Head>
        <title>Manohar&apos;sPortfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className=" pt-0 md:pt-16 sm:pt-8">
          <div className=" flex items-center justify-between w-full lg:flex-col">
            <div className=" w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt=" Image"
                className=" w-full h-auto mt-32 lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw,(max-width:1200px) 50vw, 50vw"
              />
            </div>
            <div className=" w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Crafting Digital Experiences, One Pixel at a Time."
                className=" !text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className=" my-4 text-base font-medium dark:text-light md:text-sm sm:text-xs">
                Using meticulous design and precise coding, we expertly shape
                digital landscapes, crafting seamless and immersive online
                experiences for every client.
              </p>
              <div className=" flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/ManoharGuptaResume.pdf"
                  target="blank"
                  className=" flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                   hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark dark:bg-light
                    dark:text-dark hover:dark:text-light hover:dark:bg-dark hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className=" w-6 ml-1 " />
                </Link>
                <button
                  onClick={handleOpenContactForm} // Add onClick event to open contact form
                  className=" ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </button>
              </div>
            </div>
          </div>
        </Layout>
        <Hireme />
        <div className=" absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulB} alt="Image" className=" w-full h-auto" />
        </div>
      </main>
      {isContactFormOpen && (
        <div
          className="fixed bg-dark/90 dark:bg-light/75 backdrop-blur-md py-32 sm:py-24 rounded-lg min-w-[90vw] 
         flex flex-col justify-between items-center top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 sm:min-w-[100vw] "
        >
          <button
            onClick={() => setIsContactFormOpen(false)}
            className="absolute sm:relative sm:top-0 sm:left-32 top-8 right-4 m-4 text-light flex flex-col z-60"
            aria-label="Close"
          >
            {/* Close Icon */}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-10 w-10 text-light dark:text-dark hover:text-blue-500"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
          {/* <button
            onClick={() => setIsContactFormOpen(false)} // Add onClick event to close the contact form
            className="absolute sm:relative sm:top-0 sm:left-32 top-8 right-4 m-4 text-light flex flex-col z-60"
            aria-label="Close"
          >
            <span
              className={`bg-light dark:bg-dark transition-all duration-300 block h-0.5 w-6 rounded-sm -rotate-45 translate-y-1`}
            ></span>
            <span
              className={`bg-light dark:bg-dark transition-all duration-300 block h-0.5 w-6 rounded-sm rotate-45 translate-y-1`}
            ></span>
          </button> */}
          <div className=" min-w-[40%] sm:w-full bg-light dark:bg-dark dark:bg-opacity-50 p-8 rounded-lg">
            <form
              className=" mx-auto p-6 bg-light rounded-md shadow-md"
              onSubmit={sendEmail}
            >
              <div className="mb-4">
                <label
                  htmlFor="name"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="from_name"
                  className="w-full border rounded-md p-2 focus:outline-none focus:border-blue-500"
                  required
                />
              </div>
              <div className="mb-4">
                <label
                  htmlFor="email"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="from_email"
                  className="w-full border rounded-md p-2 focus:outline-none focus:border-blue-500"
                  required
                />
              </div>
              <div className="mb-4">
                <label
                  htmlFor="Phone Number"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Phone Number
                </label>
                <input
                  type="telephone"
                  pattern="[0-9]*"
                  id="phonenumber"
                  name="from_phone_number"
                  className="w-full border rounded-md p-2 focus:outline-none focus:border-blue-500"
                  required
                />
              </div>
              <div className="mb-6">
                <label
                  htmlFor="message"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Message
                </label>
                <textarea
                  id="message"
                  name="message"
                  rows="5"
                  className="w-full border rounded-md p-2 focus:outline-none focus:border-blue-500"
                  required
                ></textarea>
              </div>
              <div className="text-center">
                <button
                  type="submit"
                  className="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600"
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </>
  );
}
